apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name  }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.member.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.member.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      securityContext:
        {{- toYaml .Values.member.podSecurityContext | nindent 8 }}
      containers:
        - name: member
          securityContext:
            {{- toYaml .Values.member.securityContext | nindent 12 }}
          image: "{{ .Values.member.image.repository }}:{{ .Values.member.image.tag }}"
          imagePullPolicy: {{ .Values.member.image.pullPolicy }}
          resources:
              requests:
                memory: "600Mi"
                cpu: "400m"
              limits:
                memory: "1000Mi"
                cpu: "600m"
          env:
            - name: ASPNETCORE_URLS
              value: http://*:8080
            - name: ProtoActor__AdvertisedHost
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
