member:
  replicaCount: 1

  image:
    repository: filip8600/cssimulator
    pullPolicy: Always
    tag: "latest"

  podAnnotations: {}

  podSecurityContext:
    runAsUser: 101

  securityContext:
    allowPrivilegeEscalation: false

  service:
    type: ClusterIP
    port: 5000

  


